# FIPS 140-3 Compliance Configuration:
# - GOFIPS140=v1.26.0: Embeds Go's native FIPS 140-3 cryptographic module (certified A6650)
# - Plugin processes inherit GODEBUG=fips140=on from parent Velero process
# - CGO_ENABLED=0: GOFIPS140 is pure Go, no CGO/OpenSSL dependencies required
#   (see https://go.dev/blog/fips140 - "written in pure Go (and Go assembly)")
# - Required to match Velero's FIPS capabilities for regulated OpenShift deployments

FROM --platform=$BUILDPLATFORM quay.io/konveyor/builder:ubi9-latest AS builder
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV GOPATH=$APP_ROOT
ENV GOFIPS140=v1.26.0

COPY . $APP_ROOT/src/velero-plugin-for-microsoft-azure

WORKDIR $APP_ROOT/src/velero-plugin-for-microsoft-azure

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -v -o $APP_ROOT/bin/velero-plugin-for-microsoft-azure -mod=mod ./velero-plugin-for-microsoft-azure

FROM registry.access.redhat.com/ubi9-minimal
RUN mkdir /plugins
COPY --from=builder /opt/app-root/bin/velero-plugin-for-microsoft-azure /plugins/
USER 65534:65534
ENTRYPOINT ["/bin/bash", "-c", "cp /plugins/* /target/."]
